### ISSUE TITLE
extend docs

### ISSUE THREAD

**Issue by kvlahromei** [CitySDK/Fix-Europe-Client#1]
Hi, while CitySDK sounds pretty interesting, sadly this repo doesn't tell much:
- what is it for?
- what are the features?
- is it extendable for third party CitySDK servers?
- ...

It would be very nice, if you could add some more infos about this aspects. So others can decide, if they are able to recycle / adapt this project.

**Comment by rjflp** [comment]
Hi,

Sorry for the delay.
Just added a few links and a description to the readme.md.
There is a paper were you can find lots of information.

Best regards
Ricardo Lopes Pereira
